name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: llamaindex/llama-deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push with Bake (multi-platform)
        uses: docker/bake-action@v4
        with:
          files: ./docker/docker-bake.hcl
          targets: all
          push: true
          set: |
            *.platform=linux/amd64,linux/arm64
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_TAG_SUFFIX=latest
